name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Run Checkstyle
        ##TODO
        run: mvn -B -DskipTests verify checkstyle:checkstyle

      - name: Run Maven Test
        ##TODO
        run: mvn test jacoco:report

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
            name: code-reports
            path: target/site
            retention-days: 14


  
  