name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        ##TODO
        run: mvn site

      - name: Run Checkstyle
        ##TODO
        run: mvn -B -D skipTests verify checkstyle:checkstyle

      - name: Upload Checkstyle Result
        ##TODO
        uses: actions/upload-artifact@v4
        with:
          path: target/site

      - name: Run Maven Test
        ##TODO
        run: mvn test jacoco:report

      - name: Jacoco Report
        ##TODO
        uses: actions/upload-artifact@v4
        with:
          path: target/site


  
  